test_size: 0.2
random_state: 42
outlier_threshold: 3
param_grid:
  n_estimators: [140,150, 160, 170]
  learning_rate: [ 0.1, 0.15, 0.2]
  max_depth: [4, 5, 6]
submission_filepath: data/08_reporting/dengue_submission.csv
feature_names:
  - city                                    
  - year                                    
  - weekofyear                               
  - week_start_date                        
  - ndvi_ne                                
  - ndvi_nw                                
  - ndvi_se                                
  - ndvi_sw                                
  - precipitation_amt_mm                   
  - reanalysis_air_temp_k                  
  - reanalysis_avg_temp_k                  
  - reanalysis_dew_point_temp_k            
  - reanalysis_max_air_temp_k              
  - reanalysis_min_air_temp_k              
  - reanalysis_precip_amt_kg_per_m2        
  - reanalysis_relative_humidity_percent   
  - reanalysis_sat_precip_amt_mm           
  - reanalysis_specific_humidity_g_per_kg
  - reanalysis_tdtr_k
  - station_avg_temp_c
  - station_diur_temp_rng_c
  - station_max_temp_c
  - station_min_temp_c
  - station_precip_mm
  - month